import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css';

import { Inter } from 'next/font/google'
import { Providers } from './redux/providers';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Manish',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
